using System.Text.Json;

namespace Scribe.AsrCheck.Scenarios;

/// <summary>One committed base phrase, decoded to 16 kHz mono float.</summary>
internal sealed record BaseClip(string Name, string File, string Text, string Voice, string Role, bool Asserted, float[] Samples)
{
    public double Seconds => Samples.Length / (double)AudioTransforms.BaseRate;
}

/// <summary>
/// The committed base phrases: the four smoke fixtures (<c>fixtures.json</c>, which the plain AsrCheck
/// run gates on) plus the scenario phrases (<c>scenario-fixtures.json</c>, generated by
/// <c>scripts/New-ScenarioFixtures.ps1</c>). The two manifests stay separate on purpose; see that script.
/// </summary>
internal sealed class BaseLibrary
{
    public const string SmokeManifest = "fixtures.json";
    public const string ScenarioManifest = "scenario-fixtures.json";

    private readonly Dictionary<string, BaseClip> _byName;

    private BaseLibrary(List<BaseClip> clips, string directory)
    {
        Clips = clips;
        Directory = directory;
        _byName = clips.ToDictionary(c => c.Name, StringComparer.Ordinal);
    }

    public IReadOnlyList<BaseClip> Clips { get; }

    public string Directory { get; }

    public BaseClip this[string name] => _byName.TryGetValue(name, out var clip)
        ? clip
        : throw new InvalidOperationException(
            $"Base fixture '{name}' is missing from {Directory}. Regenerate with scripts/New-ScenarioFixtures.ps1.");

    public bool Contains(string name) => _byName.ContainsKey(name);

    /// <summary>
    /// Ordinary dictation that long-dictation scenarios concatenate. Snippet triggers are left out
    /// (they would expand mid-dictation) and so is the unasserted numbers phrase.
    /// </summary>
    public IReadOnlyList<BaseClip> DictationPlaylist =>
        Clips.Where(c => c.Asserted && c.Role is "smoke" or "dictionary" or "speech").ToList();

    public static BaseLibrary Load(string directory)
    {
        var clips = new List<BaseClip>();
        clips.AddRange(ReadManifest(directory, SmokeManifest, smoke: true));
        clips.AddRange(ReadManifest(directory, ScenarioManifest, smoke: false));
        return new BaseLibrary(clips, directory);
    }

    private static IEnumerable<BaseClip> ReadManifest(string directory, string manifestName, bool smoke)
    {
        var manifestPath = Path.Combine(directory, manifestName);
        if (!System.IO.File.Exists(manifestPath))
        {
            throw new FileNotFoundException(
                $"{manifestName} was not found in {directory}. The base fixtures are committed under tests/fixtures/speech.",
                manifestPath);
        }

        using var document = JsonDocument.Parse(System.IO.File.ReadAllText(manifestPath));
        var clips = new List<BaseClip>();
        foreach (var entry in document.RootElement.EnumerateObject())
        {
            var file = entry.Value.GetProperty("file").GetString()!;
            var text = entry.Value.GetProperty("text").GetString()!;
            var samples = WavReader.ReadMonoFloat(Path.Combine(directory, file), out var sampleRate);
            if (sampleRate != AudioTransforms.BaseRate)
            {
                throw new InvalidDataException($"{file} is {sampleRate} Hz; base fixtures must be 16 kHz.");
            }

            clips.Add(new BaseClip(
                entry.Name,
                file,
                text,
                smoke ? "not recorded (smoke fixture)" : entry.Value.GetProperty("voice").GetString()!,
                smoke ? "smoke" : entry.Value.GetProperty("role").GetString()!,
                smoke || entry.Value.GetProperty("asserted").GetBoolean(),
                samples));
        }

        return clips;
    }
}

/// <summary>Where one base phrase sits inside a scenario, in samples at <see cref="ScenarioAudio.PlacementRate"/>.</summary>
internal sealed record Placement(string Clip, string Text, int Start, int Length)
{
    public int End => Start + Length;
}

/// <summary>A scenario's device bytes, their declared format, and where each spoken phrase is.</summary>
internal sealed record ScenarioAudio(byte[] Data, NAudio.Wave.WaveFormat Format, IReadOnlyList<Placement> Placements, int PlacementRate);

internal enum Expectation
{
    /// <summary>Speech the pipeline should decode.</summary>
    Transcribe,

    /// <summary>Silence or non-speech: nothing may be inserted and nothing may be stored in history.</summary>
    NothingToInsert,
}

internal enum LongKind
{
    /// <summary>Phrases separated by natural pauses; seams should land in a pause.</summary>
    Natural,

    /// <summary>Phrases butted together with no pause; seams must fall inside inter-word lulls.</summary>
    Dense,
}

internal enum AutoStopExpectation
{
    /// <summary>Speech then silence: stop exactly one hold window after the last voiced buffer.</summary>
    StopAfterSpeech,

    /// <summary>A short pause between phrases must not stop the recording.</summary>
    NoStopDuringPause,

    /// <summary>No speech at all: stop on the lead-in limit, reporting that no speech was heard.</summary>
    LeadInStop,

    /// <summary>Behaviour is recorded, not asserted.</summary>
    Report,
}

internal sealed record ExpectedPart(string Name, string Text, double MinOverlap);

internal sealed class ScenarioDefinition
{
    public required string Name { get; init; }

    public required char Category { get; init; }

    public required string Title { get; init; }

    public required bool Quick { get; init; }

    public required IReadOnlyList<string> Sources { get; init; }

    public required string Transform { get; init; }

    public required DeviceFormat Device { get; init; }

    public required string ExpectedBehavior { get; init; }

    public required Func<ScenarioAudio> Build { get; init; }

    public string? ExpectedText { get; init; }

    public Expectation Expectation { get; init; } = Expectation.Transcribe;

    /// <summary>Asserted word overlap with <see cref="ExpectedText"/>; null means reported only.</summary>
    public double? MinOverlap { get; init; }

    /// <summary>Production default is on; exact-length chunk-boundary cases switch it off.</summary>
    public bool UseVad { get; init; } = true;

    public IReadOnlyList<ExpectedPart>? Parts { get; init; }

    public LongKind? Long { get; init; }

    public AutoStopExpectation? AutoStop { get; init; }

    /// <summary>Also decode with VAD off, to see what the recogniser alone makes of non-speech.</summary>
    public bool ProbeWithoutVad { get; init; }
}

/// <summary>
/// Every scenario, derived deterministically from the base phrases. Categories follow the suite's
/// brief: A clean, B device formats, C level and signal, D noise and room, E timing and structure,
/// F long dictation, G silence auto-stop, M multilingual model samples (when present).
/// </summary>
internal static class ScenarioCatalog
{
    private const int Rate = AudioTransforms.BaseRate;

    // Every live microphone has an analogue floor. -70 dBFS RMS sits far under the silence
    // auto-stop threshold and under anything VAD calls speech, while keeping "silence" from being
    // exact digital zeros, which only a muted endpoint delivers.
    private const double RoomFloorDbfs = -70;

    public static IReadOnlyList<ScenarioDefinition> Build(BaseLibrary library, string? modelSamplesDirectory)
    {
        var scenarios = new List<ScenarioDefinition>();
        scenarios.AddRange(Clean(library));
        scenarios.AddRange(DeviceFormats(library));
        scenarios.AddRange(LevelAndSignal(library));
        scenarios.AddRange(NoiseAndRoom(library));
        scenarios.AddRange(TimingAndStructure(library));
        scenarios.AddRange(LongDictation(library));
        scenarios.AddRange(SilenceAutoStop(library));
        scenarios.AddRange(ModelSamples(modelSamplesDirectory));
        return scenarios;
    }

    private static IEnumerable<ScenarioDefinition> Clean(BaseLibrary library)
    {
        foreach (var clip in library.Clips)
        {
            yield return new ScenarioDefinition
            {
                Name = $"A-clean-{clip.Name}",
                Category = 'A',
                Title = $"clean {clip.Name}",
                Quick = true,
                Sources = [clip.Name],
                Transform = "none (the committed fixture as-is)",
                Device = DeviceFormat.Canonical,
                ExpectedText = clip.Text,
                MinOverlap = clip.Asserted ? Program.MinimumWordOverlap : null,
                ExpectedBehavior = clip.Asserted
                    ? "decodes the phrase"
                    : "decodes the phrase; number formatting is not a contract, so reported only",
                Build = () => Canonical(clip.Samples, [Whole(clip)]),
            };
        }
    }

    private static IEnumerable<ScenarioDefinition> DeviceFormats(BaseLibrary library)
    {
        var floor = "-60 dBFS broadband floor per channel at the device rate";

        yield return Device(library, "B-16k-mono-pcm16", "16 kHz mono 16-bit (the canonical format)", "dict-azure-devops",
            DeviceFormat.Canonical, floor, asserted: true,
            (speech, rate, seed) => [WithFloor(speech, rate, -60, seed)]);

        yield return Device(library, "B-44k1-stereo-pcm16", "44.1 kHz stereo 16-bit", "sentence",
            new DeviceFormat("44.1 kHz stereo 16-bit PCM (extensible)", 44_100, 2, SampleEncoding.Pcm16, true), floor, asserted: true,
            (speech, rate, seed) => [WithFloor(speech, rate, -60, seed), WithFloor(speech, rate, -60, seed + 1)]);

        yield return Device(library, "B-48k-stereo-float", "48 kHz stereo float", "dict-scribe",
            Float48(2), floor, asserted: true,
            (speech, rate, seed) => [WithFloor(speech, rate, -60, seed), WithFloor(speech, rate, -60, seed + 1)]);

        yield return Device(library, "B-48k-stereo-float-silent-right", "48 kHz stereo float, dead second channel",
            "dict-github-copilot", Float48(2), "left: speech plus floor; right: exact digital silence", asserted: true,
            (speech, rate, seed) => [WithFloor(speech, rate, -60, seed), new float[speech.Length]]);

        var foreign = library["question"];
        yield return new ScenarioDefinition
        {
            Name = "B-48k-stereo-float-foreign-right",
            Category = 'B',
            Title = "48 kHz stereo float, another voice on channel 2 at -6 dB",
            Quick = true,
            Sources = ["sentence", foreign.Name],
            Transform = "left: 'sentence' plus floor; right: 'question' (a different voice) 6 dB below the left peak",
            Device = Float48(2),
            ExpectedText = library["sentence"].Text,
            MinOverlap = null,
            ExpectedBehavior = "decodes the left-channel phrase; the averaged foreign voice is measured, not asserted",
            Build = () =>
            {
                var left = AudioTransforms.Resample(library["sentence"].Samples, Rate, 48_000);
                var right = AudioTransforms.Resample(foreign.Samples, Rate, 48_000);
                right = AudioTransforms.Scale(
                    AudioTransforms.PadTo(right, left.Length)[..left.Length],
                    AudioTransforms.Peak(left) * AudioTransforms.FromDbfs(-6) / Math.Max(1e-9f, AudioTransforms.Peak(right)));
                var seed = StableSeed("B-48k-stereo-float-foreign-right");
                return Encode(Float48(2), [WithFloor(left, 48_000, -60, seed), WithFloor(right, 48_000, -60, seed + 1)],
                    [Whole(library["sentence"], 48_000)], 48_000);
            },
        };

        yield return Device(library, "B-96k-mono-float", "96 kHz mono float", "question",
            new DeviceFormat("96 kHz mono 32-bit float (extensible)", 96_000, 1, SampleEncoding.Float32, true), floor, asserted: true,
            (speech, rate, seed) => [WithFloor(speech, rate, -60, seed)]);

        yield return Device(library, "B-8k-mono-pcm16", "8 kHz mono 16-bit (narrowband, upsampled by the pipeline)", "list",
            new DeviceFormat("8 kHz mono 16-bit PCM (extensible)", 8_000, 1, SampleEncoding.Pcm16, true), floor, asserted: false,
            (speech, rate, seed) => [WithFloor(speech, rate, -60, seed)]);

        yield return Device(library, "B-48k-6ch-float", "48 kHz 6-channel float (array microphone)", "longer",
            Float48(6), "each channel: speech with a 0 to 3 sample inter-microphone delay, 0 to -2.5 dB gain, independent floor",
            asserted: true,
            (speech, rate, seed) =>
            {
                int[] delays = [0, 1, 2, 3, 2, 1];
                var channels = new List<float[]>();
                for (var channel = 0; channel < delays.Length; channel++)
                {
                    var gain = AudioTransforms.FromDbfs(-0.5 * channel);
                    channels.Add(WithFloor(
                        AudioTransforms.Scale(AudioTransforms.Delay(speech, delays[channel]), gain), rate, -60, seed + channel));
                }

                return channels;
            });
    }

    private static IEnumerable<ScenarioDefinition> LevelAndSignal(BaseLibrary library)
    {
        yield return Transformed(library, "C-quiet-40dbfs", "quiet input, -40 dBFS peak", "greeting",
            "peak normalized to -40 dBFS over a -90 dBFS floor", asserted: false,
            s => WithFloor(AudioTransforms.NormalizePeak(s, -40), Rate, -90, StableSeed("C-quiet")));

        yield return Transformed(library, "C-hot-clipped", "hot input, +12 dB then hard clipped", "pangram",
            "+12 dB gain, hard clip at full scale", asserted: false,
            s => AudioTransforms.HardClip(AudioTransforms.Scale(s, AudioTransforms.FromDbfs(12))));

        yield return Transformed(library, "C-dc-offset", "DC offset of +0.1 (-20 dBFS)", "sentence",
            "+0.1 constant offset", asserted: false,
            s => AudioTransforms.HardClip(AudioTransforms.AddConstant(s, 0.1f)));

        yield return Transformed(library, "C-hum-50hz", "50 Hz mains hum with 150 and 250 Hz harmonics", "longer",
            "hum at -26 dBFS peak", asserted: false,
            s => AudioTransforms.HardClip(AudioTransforms.AddHum(s, Rate, AudioTransforms.FromDbfs(-26))));
    }

    private static IEnumerable<ScenarioDefinition> NoiseAndRoom(BaseLibrary library)
    {
        foreach (var snr in new[] { 20, 10, 5, 0 })
        {
            var name = $"D-white-{snr:00}db";
            yield return Transformed(library, name, $"white noise at {snr} dB SNR", "sentence",
                $"Gaussian white noise at {snr} dB below the active speech level", asserted: snr >= 20,
                s => AudioTransforms.MixAtSnr(s, AudioTransforms.WhiteNoise(s.Length, 1, StableSeed(name)), snr, Rate),
                quick: snr == 10);
        }

        foreach (var snr in new[] { 20, 10, 5, 0 })
        {
            var name = $"D-pink-{snr:00}db";
            yield return Transformed(library, name, $"pink noise at {snr} dB SNR", "longer",
                $"pink (1/f) noise at {snr} dB below the active speech level", asserted: snr >= 20,
                s => AudioTransforms.MixAtSnr(s, AudioTransforms.PinkNoise(s.Length, 1, StableSeed(name)), snr, Rate),
                quick: snr == 0);
        }

        string[] talkers = ["question", "list", "dict-azure-devops"];
        yield return new ScenarioDefinition
        {
            Name = "D-babble-10db",
            Category = 'D',
            Title = "babble: three other voices mixed at 10 dB SNR",
            Quick = true,
            Sources = ["pangram", .. talkers],
            Transform = "'question', 'list' and 'dict-azure-devops' looped from seeded offsets, summed, 10 dB under the target",
            Device = DeviceFormat.Canonical,
            ExpectedText = library["pangram"].Text,
            ExpectedBehavior = "decodes the foreground phrase; competing words are measured, not asserted",
            Build = () =>
            {
                var target = library["pangram"];
                var babble = AudioTransforms.Babble(
                    target.Samples.Length, talkers.Select(t => library[t].Samples).ToList(), Rate, StableSeed("D-babble"));
                return Canonical(AudioTransforms.MixAtSnr(target.Samples, babble, 10, Rate), [Whole(target)]);
            },
        };

        yield return Transformed(library, "D-reverb-light", "light room reverb (RT60 0.4 s)", "greeting",
            "Schroeder reverb, RT60 0.4 s, 30 percent wet", asserted: false,
            s => AudioTransforms.Reverb(s, Rate, 0.4, 0.3), quick: false);

        yield return Transformed(library, "D-reverb-heavy", "heavy room reverb (RT60 1.0 s)", "greeting",
            "Schroeder reverb, RT60 1.0 s, 60 percent wet", asserted: false,
            s => AudioTransforms.Reverb(s, Rate, 1.0, 0.6), quick: true);
    }

    private static IEnumerable<ScenarioDefinition> TimingAndStructure(BaseLibrary library)
    {
        var scribe = library["dict-scribe"];
        yield return new ScenarioDefinition
        {
            Name = "E-lead-silence-3s",
            Category = 'E',
            Title = "3 s of room tone before speech",
            Quick = true,
            Sources = [scribe.Name],
            Transform = "3 s of -70 dBFS floor, the phrase, 0.5 s of floor",
            Device = DeviceFormat.Canonical,
            ExpectedText = scribe.Text,
            MinOverlap = Program.MinimumWordOverlap,
            ExpectedBehavior = "VAD trims the lead-in and the phrase decodes",
            Build = () => Sequence("E-lead", [Pause(3.0), scribe, Pause(0.5)]),
        };

        var question = library["question"];
        yield return new ScenarioDefinition
        {
            Name = "E-trail-silence-5s",
            Category = 'E',
            Title = "5 s of room tone after speech",
            Quick = true,
            Sources = [question.Name],
            Transform = "0.3 s of floor, the phrase, 5 s of -70 dBFS floor",
            Device = DeviceFormat.Canonical,
            ExpectedText = question.Text,
            MinOverlap = Program.MinimumWordOverlap,
            ExpectedBehavior = "VAD trims the tail and the phrase decodes",
            Build = () => Sequence("E-trail", [Pause(0.3), question, Pause(5.0)]),
        };

        var first = library["dict-kubernetes"];
        var second = library["list"];
        yield return new ScenarioDefinition
        {
            Name = "E-mid-pause-2s",
            Category = 'E',
            Title = "a 2 s pause in the middle of an utterance",
            Quick = true,
            Sources = [first.Name, second.Name],
            Transform = "phrase, 2 s of -70 dBFS floor, phrase",
            Device = DeviceFormat.Canonical,
            ExpectedText = $"{first.Text} {second.Text}",
            ExpectedBehavior = "both halves survive VAD trimming",
            Parts =
            [
                new ExpectedPart("first half", first.Text, Program.MinimumWordOverlap),
                new ExpectedPart("second half", second.Text, Program.MinimumWordOverlap),
            ],
            Build = () => Sequence("E-mid", [Pause(0.3), first, Pause(2.0), second, Pause(0.3)]),
        };

        var pangram = library["pangram"];
        yield return new ScenarioDefinition
        {
            Name = "E-burst-250ms",
            Category = 'E',
            Title = "a 0.25 s speech burst",
            Quick = true,
            Sources = [pangram.Name],
            Transform = "the loudest 250 ms of the phrase with 5 ms fades, 0.5 s of floor either side",
            Device = DeviceFormat.Canonical,
            ExpectedBehavior = "reported: VAD's 0.25 s minimum speech length sits right at this burst",
            Build = () =>
            {
                var burst = AudioTransforms.LoudestWindow(pangram.Samples, Rate, 0.25);
                var seed = StableSeed("E-burst");
                var audio = AudioTransforms.Concat(
                    AudioTransforms.Floor(Rate / 2, RoomFloorDbfs, seed),
                    AudioTransforms.Add(burst, AudioTransforms.Floor(burst.Length, RoomFloorDbfs, seed + 1)),
                    AudioTransforms.Floor(Rate / 2, RoomFloorDbfs, seed + 2));
                return Canonical(audio, [new Placement(pangram.Name, "(fragment)", Rate / 2, burst.Length)]);
            },
        };

        yield return new ScenarioDefinition
        {
            Name = "E-digital-silence-2s",
            Category = 'E',
            Title = "2 s of pure digital silence (a muted endpoint)",
            Quick = true,
            Sources = [],
            Transform = "exact zeros",
            Device = DeviceFormat.Canonical,
            Expectation = Expectation.NothingToInsert,
            ProbeWithoutVad = true,
            ExpectedBehavior = "nothing to insert, nothing stored in history (the muted-microphone path)",
            Build = () => Canonical(AudioTransforms.Silence(2.0, Rate), []),
        };

        yield return new ScenarioDefinition
        {
            Name = "E-clicks-only-2s",
            Category = 'E',
            Title = "2 s of clicks over room tone, no speech",
            Quick = true,
            Sources = [],
            Transform = "six 2 ms decaying clicks at -6 dBFS peak over a -70 dBFS floor",
            Device = DeviceFormat.Canonical,
            Expectation = Expectation.NothingToInsert,
            ProbeWithoutVad = true,
            ExpectedBehavior = "nothing to insert, nothing stored in history",
            Build = () => Canonical(
                AudioTransforms.Clicks(2.0, Rate, [0.15, 0.42, 0.81, 1.10, 1.47, 1.83], -6, StableSeed("E-clicks")), []),
        };

        yield return new ScenarioDefinition
        {
            Name = "E-noise-only-3s",
            Category = 'E',
            Title = "3 s of pink noise, no speech",
            Quick = false,
            Sources = [],
            Transform = "pink noise at -35 dBFS RMS",
            Device = DeviceFormat.Canonical,
            ProbeWithoutVad = true,
            ExpectedBehavior = "reported: what VAD and the recogniser make of steady noise",
            Build = () => Canonical(AudioTransforms.PinkNoise(3 * Rate, AudioTransforms.FromDbfs(-35), StableSeed("E-noise")), []),
        };
    }

    private static IEnumerable<ScenarioDefinition> LongDictation(BaseLibrary library)
    {
        (int Seconds, bool Vad, bool Quick, LongKind Kind)[] cases =
        [
            (29, true, false, LongKind.Natural),
            (30, false, true, LongKind.Natural),
            (30, true, false, LongKind.Natural),
            (31, true, true, LongKind.Natural),
            (31, false, false, LongKind.Natural),
            (60, true, false, LongKind.Natural),
            (120, true, false, LongKind.Natural),
            (300, true, false, LongKind.Natural),
            (60, true, false, LongKind.Dense),
        ];

        foreach (var (seconds, vad, quick, kind) in cases)
        {
            var name = $"F-{(kind == LongKind.Dense ? "dense" : "long")}-{seconds:000}s{(vad ? string.Empty : "-exact")}";
            var playlist = library.DictationPlaylist;
            yield return new ScenarioDefinition
            {
                Name = name,
                Category = 'F',
                Title = $"{seconds} s {(kind == LongKind.Dense ? "back-to-back speech with no pauses" : "dictation")}{(vad ? string.Empty : ", VAD off so Transcribe sees exactly this length")}",
                Quick = quick,
                Sources = playlist.Select(c => c.Name).ToList(),
                Transform = kind == LongKind.Dense
                    ? "phrases trimmed to their speech and butted together; remainder is trailing floor"
                    : "phrases trimmed to their speech, separated by 0.25 s or longer floor pauses stretched to fill exactly",
                Device = DeviceFormat.Canonical,
                UseVad = vad,
                Long = kind,
                ExpectedBehavior = kind == LongKind.Dense
                    ? "reported: seams have to cut inside continuous speech"
                    : "every phrase decodes; a chunk seam that lands in a pause drops and duplicates nothing",
                Build = () => LongAudio(playlist, seconds, kind, StableSeed(name)),
            };
        }
    }

    private static IEnumerable<ScenarioDefinition> SilenceAutoStop(BaseLibrary library)
    {
        yield return AutoStop(library, "G-stop-after-speech", "speech then 6 s of room tone", AutoStopExpectation.StopAfterSpeech,
            ["greeting"], [Pause(0.2), library["greeting"], Pause(6.0)]);

        yield return AutoStop(library, "G-pink-noise-after-speech", "speech then 8 s of pink noise at -30 dBFS RMS",
            AutoStopExpectation.Report, ["greeting"], [Pause(0.2), library["greeting"], Noise(8.0, pink: true, -30)]);

        yield return AutoStop(library, "G-low-noise-after-speech", "speech then 8 s of white noise at -55 dBFS RMS",
            AutoStopExpectation.Report, ["greeting"], [Pause(0.2), library["greeting"], Noise(8.0, pink: false, -55)]);

        yield return AutoStop(library, "G-quiet-speech", "speech at -40 dBFS peak then 8 s of room tone",
            AutoStopExpectation.Report, ["sentence"],
            [Pause(0.2), library["sentence"] with { Samples = AudioTransforms.NormalizePeak(library["sentence"].Samples, -40) }, Pause(8.0)]);

        yield return AutoStop(library, "G-pause-2s-no-stop", "speech, a 2 s pause, speech, then room tone",
            AutoStopExpectation.NoStopDuringPause, ["pangram", "list"],
            [Pause(0.2), library["pangram"], Pause(2.0), library["list"], Pause(6.0)]);

        yield return AutoStop(library, "G-pause-5s", "speech, a 5 s pause, speech",
            AutoStopExpectation.Report, ["pangram", "list"],
            [Pause(0.2), library["pangram"], Pause(5.0), library["list"], Pause(2.0)]);

        yield return AutoStop(library, "G-silence-12s", "12 s of room tone, nobody speaks",
            AutoStopExpectation.LeadInStop, [], [Pause(12.0)]);
    }

    private static IEnumerable<ScenarioDefinition> ModelSamples(string? directory)
    {
        if (directory is null || !System.IO.Directory.Exists(directory))
        {
            yield break;
        }

        foreach (var path in System.IO.Directory.GetFiles(directory, "*.wav").OrderBy(p => p, StringComparer.Ordinal))
        {
            var language = Path.GetFileNameWithoutExtension(path);
            yield return new ScenarioDefinition
            {
                Name = $"M-model-sample-{language}",
                Category = 'M',
                Title = $"model sample '{language}' (downloaded with the model, not committed)",
                Quick = true,
                Sources = [Path.GetFileName(path)],
                Transform = "none; its own rate goes through the production resampler",
                Device = new DeviceFormat("as stored", 0, 0, SampleEncoding.Pcm16, false),
                ExpectedBehavior = "reported: no reference transcript ships with these samples",
                Build = () =>
                {
                    var (data, format) = DeviceAudio.ReadWav(path);
                    return new ScenarioAudio(data, format, [], format.SampleRate);
                },
            };
        }
    }

    private static ScenarioDefinition Device(
        BaseLibrary library,
        string name,
        string title,
        string source,
        DeviceFormat format,
        string transform,
        bool asserted,
        Func<float[], int, int, IReadOnlyList<float[]>> channels)
    {
        var clip = library[source];
        return new ScenarioDefinition
        {
            Name = name,
            Category = 'B',
            Title = title,
            Quick = true,
            Sources = [clip.Name],
            Transform = $"resampled to {format.SampleRate} Hz for synthesis; {transform}",
            Device = format,
            ExpectedText = clip.Text,
            MinOverlap = asserted ? Program.MinimumWordOverlap : null,
            ExpectedBehavior = asserted
                ? "the production conversion is transparent: the phrase decodes"
                : "decodes the phrase; the band-limited source is measured, not asserted",
            Build = () =>
            {
                var speech = AudioTransforms.Resample(clip.Samples, Rate, format.SampleRate);
                return Encode(format, channels(speech, format.SampleRate, StableSeed(name)), [Whole(clip, format.SampleRate)], format.SampleRate);
            },
        };
    }

    private static ScenarioDefinition Transformed(
        BaseLibrary library,
        string name,
        string title,
        string source,
        string transform,
        bool asserted,
        Func<float[], float[]> apply,
        bool quick = true)
    {
        var clip = library[source];
        return new ScenarioDefinition
        {
            Name = name,
            Category = name[0],
            Title = title,
            Quick = quick,
            Sources = [clip.Name],
            Transform = transform,
            Device = DeviceFormat.Canonical,
            ExpectedText = clip.Text,
            MinOverlap = asserted ? Program.MinimumWordOverlap : null,
            ExpectedBehavior = asserted ? "decodes the phrase" : "reported: how far the condition degrades the decode",
            Build = () => Canonical(apply(clip.Samples), [Whole(clip)]),
        };
    }

    private static ScenarioDefinition AutoStop(
        BaseLibrary library,
        string name,
        string title,
        AutoStopExpectation expectation,
        IReadOnlyList<string> sources,
        IReadOnlyList<object> parts)
    {
        _ = library;
        var spoken = parts.OfType<BaseClip>().ToList();
        return new ScenarioDefinition
        {
            Name = name,
            Category = 'G',
            Title = title,
            Quick = true,
            Sources = sources,
            Transform = "48 kHz stereo float, fed to the production tracker in 10 ms buffers",
            Device = Float48(2),
            ExpectedText = spoken.Count == 0 ? null : string.Join(' ', spoken.Select(c => c.Text)),
            AutoStop = expectation,
            MinOverlap = expectation is AutoStopExpectation.StopAfterSpeech or AutoStopExpectation.NoStopDuringPause
                ? Program.MinimumWordOverlap
                : null,
            ExpectedBehavior = expectation switch
            {
                AutoStopExpectation.StopAfterSpeech => "stops one hold window after the last voiced buffer; the captured speech decodes",
                AutoStopExpectation.NoStopDuringPause => "keeps recording through the pause; stops after the final phrase",
                AutoStopExpectation.LeadInStop => "stops on the lead-in limit and reports that no speech was heard",
                _ => "reported",
            },
            Build = () =>
            {
                var mono = SequenceSamples(name, parts, out var placements);
                var left = AudioTransforms.Resample(mono, Rate, 48_000);
                var seed = StableSeed(name);
                var scaled = placements.Select(p => p with
                {
                    Start = (int)((long)p.Start * 48_000 / Rate),
                    Length = (int)((long)p.Length * 48_000 / Rate),
                }).ToList();
                return Encode(Float48(2),
                    [WithFloor(left, 48_000, -80, seed), WithFloor(left, 48_000, -80, seed + 1)], scaled, 48_000);
            },
        };
    }

    /// <summary>A natural-pause long dictation of exactly <paramref name="seconds"/>, for scenarios outside category F.</summary>
    internal static ScenarioAudio LongDictationAudio(BaseLibrary library, int seconds, string seedName) =>
        LongAudio(library.DictationPlaylist, seconds, LongKind.Natural, StableSeed(seedName));

    /// <summary>
    /// Concatenates whole phrases to exactly <paramref name="seconds"/>: phrases are taken in playlist
    /// order (skipping any that no longer fit) and the leftover time is spread across the pauses,
    /// so speech runs from the first sample to the last and VAD trims almost nothing. That is what
    /// makes the 29, 30 and 31 s cases land on either side of the 30 s chunk limit.
    /// </summary>
    private static ScenarioAudio LongAudio(IReadOnlyList<BaseClip> playlist, int seconds, LongKind kind, int seed)
    {
        var total = seconds * Rate;
        var minimumGap = kind == LongKind.Dense ? 0 : AudioTransforms.SamplesFor(0.25, Rate);
        var trimmed = playlist
            .Select(c => (Clip: c, Audio: AudioTransforms.TrimSilence(c.Samples, Rate, -50, kind == LongKind.Dense ? 0.02 : 0.06)))
            .Where(t => t.Audio.Length > 0)
            .ToList();

        var chosen = new List<(BaseClip Clip, float[] Audio)>();
        var used = 0;
        var misses = 0;
        for (var index = 0; misses < trimmed.Count; index++)
        {
            var candidate = trimmed[index % trimmed.Count];
            var needed = candidate.Audio.Length + (chosen.Count > 0 ? minimumGap : 0);
            if (used + needed <= total)
            {
                chosen.Add(candidate);
                used += needed;
                misses = 0;
            }
            else
            {
                misses++;
            }
        }

        var gaps = chosen.Count - 1;
        var remainder = total - used;
        var buffer = AudioTransforms.Floor(total, RoomFloorDbfs, seed);
        var placements = new List<Placement>();
        var position = 0;
        for (var i = 0; i < chosen.Count; i++)
        {
            if (i > 0)
            {
                var extra = kind == LongKind.Dense || gaps == 0 ? 0 : (remainder / gaps) + (i - 1 < remainder % gaps ? 1 : 0);
                position += minimumGap + extra;
            }

            var (clip, audio) = chosen[i];
            audio.CopyTo(buffer, position);
            placements.Add(new Placement(clip.Name, clip.Text, position, audio.Length));
            position += audio.Length;
        }

        return Canonical(buffer, placements);
    }

    private static ScenarioAudio Sequence(string seedName, IReadOnlyList<object> parts)
    {
        var samples = SequenceSamples(seedName, parts, out var placements);
        return Canonical(samples, placements);
    }

    /// <summary>
    /// Builds mono audio from phrases and pauses. Pauses are live room tone; phrases also carry the
    /// floor under them, so a phrase never starts or ends on exact digital zeros.
    /// </summary>
    private static float[] SequenceSamples(string seedName, IReadOnlyList<object> parts, out List<Placement> placements)
    {
        var seed = StableSeed(seedName);
        var pieces = new List<float[]>();
        placements = [];
        var position = 0;
        foreach (var part in parts)
        {
            float[] piece;
            switch (part)
            {
                case BaseClip clip:
                    piece = WithFloor(clip.Samples, Rate, RoomFloorDbfs, seed++);
                    placements.Add(new Placement(clip.Name, clip.Text, position, piece.Length));
                    break;
                case PauseSpec pause:
                    piece = AudioTransforms.Floor(AudioTransforms.SamplesFor(pause.Seconds, Rate), RoomFloorDbfs, seed++);
                    break;
                case NoiseSpec noise:
                    var length = AudioTransforms.SamplesFor(noise.Seconds, Rate);
                    piece = noise.Pink
                        ? AudioTransforms.PinkNoise(length, AudioTransforms.FromDbfs(noise.RmsDbfs), seed++)
                        : AudioTransforms.WhiteNoise(length, AudioTransforms.FromDbfs(noise.RmsDbfs), seed++);
                    break;
                default:
                    throw new InvalidOperationException($"Unknown sequence part {part}.");
            }

            pieces.Add(piece);
            position += piece.Length;
        }

        return AudioTransforms.Concat([.. pieces]);
    }

    private static PauseSpec Pause(double seconds) => new(seconds);

    private static NoiseSpec Noise(double seconds, bool pink, double rmsDbfs) => new(seconds, pink, rmsDbfs);

    private static Placement Whole(BaseClip clip, int rate = Rate) =>
        new(clip.Name, clip.Text, 0, (int)((long)clip.Samples.Length * rate / Rate));

    private static float[] WithFloor(float[] samples, int rate, double floorDbfs, int seed) =>
        AudioTransforms.Add(samples, AudioTransforms.Floor(samples.Length, floorDbfs, seed));

    private static ScenarioAudio Canonical(float[] samples, IReadOnlyList<Placement> placements) =>
        Encode(DeviceFormat.Canonical, [samples], placements, Rate);

    private static ScenarioAudio Encode(DeviceFormat format, IReadOnlyList<float[]> channels, IReadOnlyList<Placement> placements, int placementRate) =>
        new(DeviceAudio.Interleave(channels, format.Encoding), format.ToWaveFormat(), placements, placementRate);

    private static DeviceFormat Float48(int channels) =>
        new($"48 kHz {(channels == 2 ? "stereo" : $"{channels}-channel")} 32-bit float (extensible)", 48_000, channels, SampleEncoding.Float32, true);

    /// <summary>FNV-1a over the name: stable across processes, unlike string.GetHashCode.</summary>
    internal static int StableSeed(string name)
    {
        var hash = 2166136261u;
        foreach (var c in name)
        {
            hash = (hash ^ c) * 16777619u;
        }

        return (int)(hash & 0x7FFFFFFF);
    }

    private sealed record PauseSpec(double Seconds);

    private sealed record NoiseSpec(double Seconds, bool Pink, double RmsDbfs);
}
